# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
#COPY package*.json ./
COPY public/ /app/public
COPY src/ /app/src
COPY package.json /app/

# Install project dependencies

RUN npm install
RUN npm i --save @fortawesome/fontawesome-svg-core

# Copy the rest of the application files to the working directory
#COPY . .

# Build the React application
RUN npm run build

# Expose a port for the application (adjust if necessary)
EXPOSE 3000

# Define the command to start the application
CMD [ "npm", "start" ]
