on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: self-hosted
    steps:
      - run: docker run hello-world
        name: Basic Output

    
