on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: build
    runs-on: caner
    steps:
      - uses: actions/checkout@v4
      - run: |
          export DOCKER_DEFAULT_PLATFORM=linux/amd64
          docker container stop build-container || true
          docker container rm build-container || true
          docker image rm build-image:0.0.1 || true
        name: Cleanup
      - run: |
          docker build -t build-image:0.0.1 -f build.Dockerfile .
        name: Build
      - run: |
          docker run --name build-container build-image:0.0.1
        name: Run
      - run: |
          docker cp build-container:/app/build .
          ls -al
        name: Copy
      - run: |
          docker container rm build-container || true
          docker image rm run-image:0.0.1 || true
          docker build  --platform linux/amd64 -t run-image:0.0.1 -f run.Dockerfile .
        name: Build2
      - run: |
          docker tag run-image:0.0.1 10.0.40.160:5000/shoppinglist/test:0.0.2 
        name: tag
      - run: |
           docker push -f 10.0.40.160:5000/shoppinglist/test:0.0.2  
        name: push
        
  deploy:
    name: Deploy
    runs-on: caner
    needs: [my_job]
    steps:
      - uses: actions/checkout@v4
      - run: |
          ssh fhvdevops@10.0.40.162 'bash -s' < ./deploy.sh
        name: run command

    
