on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t shoppinglist:0.0.1 -f Dockerfile .
        name: Build
      - run: |
          docker run --name build-container shoppinglist:0.0.1
          docker cp build-container:/app/build .
        name: Run

    
