on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: self-hosted
    steps:
      - run: |
          docker build -t shoppinglist:0.0.1 -f Dockerfile .
        name: Basic Output

    
