on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: build
    runs-on: caner
    steps:
      - uses: actions/checkout@v4
      - run: |
           ping -c 10 10.0.40.160
        name: ping
      - run: |
          docker image rm build-image:0.0.1 || true
          docker build -t build-image:0.0.1 -f build.Dockerfile .
        name: Build
      - run: |
          docker container rm build-container || true 
          docker run --name build-container shoppinglist:0.0.1
        name: Run
      - run: |
          docker cp build-container:/app/build .
          ls -al
        name: Copy
      - run: |
          docker image rm run-image:0.0.1 || true
          docker build -t run-image:0.0.1 -f run.Dockerfile .
        name: Build2
      - run: |
          docker image tag run-image:0.0.1 10.0.40.160:5000/shoppinglist/test:0.0.1 
        name: tag
      - run: |
           docker image push 10.0.40.160:5000/shoppinglist/test:0.0.1  
        name: push
        
  deploy:
    name: Deploy
    runs-on: caner
    needs: {build}
    steps:
      - uses: actions/checkout@v4
      - run: |
          ssh fhvdevops@10.0.40.162 'echo "This is the run command"
        name: run command

    
